export { default as MyPageAside } from './MyPageAside'
export { default as MyPageTitle } from './MyPageTitle'
export { default as ProfileEdit } from './ProfileEdit'
export { default as ReceivedCompanion } from './ReceivedCompanion'
export { default as SentCompanion } from './SentCompanion'
export { default as OtherProfile } from './OtherProfile'
